In [5]:
#creating the numpy array by several methods
import numpy as np
# we can create the numpy array using array() in numpy object
a=np.array([[1,2,3],(1,22,3)],dtype=np.int32)# it should have same parameter of the same data type of type list
print(a)
# array funtion always take list as an argument 
# Numpy array occupies less memory as compare to list

# To create sequence of the numbers,Numpy provides the funtion analogous to range that return array insted of list 
# It is arrange()
c=np.arange(0,20,0.3)# it also accepts float increment
print(c)
d=list(range(20))
print(c)

# type of the array can be specified explicitly by passing the parameters of dtype 
c=np.array([[1,2],[3,4]],dtype=complex)
print(c)

# There is many specail funtion in numpy module, it consists of the ones() ,zeros() which is used create an numpy array 
# of zero and one respectively
# for example to create an numpy array containing zero can be made for zeros() contained in numpy module
x=np.zeros((3,4))# where 3 are the no. of rows and 4 are no. of coloums
print(x)
# np.dtype returns the type of the elements in array
print(x.ndim)
print(x.itemsize) # return the size in bytes of each elements in array

# linspace() recieves the number of the elements that we want instead of the steps followed
# it useful than arange() 
x=np.linspace(0,2,9)# where 9 is no of elements obtained between the 0 and 2
print(x)

# concatination of the numpy array
x=np.array([[2,3],[3,4]])
y=np.array([[4,5],[7,8]])
z=np.concatenate((x,y),axis=0);# concatination example of numpy array x and y along rows since axis=0(i.e no of rows incr.)
z1=np.concatenate((x,y),axis=1);# concatenation example of numpy array x and y along coloums since axis=1 
print("\n contenation operation on x and y numpy array\n",z,"\ndsfa",z1)

[[ 1  2  3]
 [ 1 22  3]]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7 15.  15.3 15.6 15.9 16.2 16.5
 16.8 17.1 17.4 17.7 18.  18.3 18.6 18.9 19.2 19.5 19.8]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7 15.  15.3 15.6 15.9 16.2 16.5
 16.8 17.1 17.4 17.7 18.  18.3 18.6 18.9 19.2 19.5 19.8]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
8
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

 contenation operation on x and y numpy array
 [[2 3]
 [3 4]
 [4 5]
 [7 8]] 
dsfa [[2 3 4 5]
 [3 4 7 8]]


In [17]:
# one dimensional are printed as row, bidimensional as matrixes and tridimensional as lists of matrixs
x=np.arange(6)
print(x)
# 2 dimensional n array
x=np.arange(12).reshape(4,3)
print(x)
# 3 dimensional numpy array
print("\n 3 dimensional array example")
x=np.arange(24).reshape(2,4,3)
print(x,"\n")

# if the array is too large to be printed,then numpy automatically skips the central part and only prints corners elements
x=np.arange(2000).reshape(4,500)
print(x)

# Arthemetic operator on the array apply elementwise and new array is created and filled with the result
y=np.arange(4).reshape(2,2)
x=np.arange(4).reshape(2,2)
print(y)
z=y;
y=y**2
print("Array after squaring the each elements of the array\n",y)

m=x*y
# matrix multipication
print(m,"\n The matrix multiplication is:")

#The matrix product can be performed using the @ operator or calling dot() funtion
m=x@y
print(m)
m=x.dot(y)
print(m)
T=m<35#...applying the boolean operation on the numpy array and returning the boolean value acc. to operation applied on it
print("\n",T)
# process of accesing the elements of numpy array 
print(m[1,1])

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 3 dimensional array example
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 

[[   0    1    2 ...  497  498  499]
 [ 500  501  502 ...  997  998  999]
 [1000 1001 1002 ... 1497 1498 1499]
 [1500 1501 1502 ... 1997 1998 1999]]
[[0 1]
 [2 3]]
Array after squaring the each elements of the array
 [[0 1]
 [4 9]]
[[ 0  1]
 [ 8 27]] 
 The matrix multiplication is:
[[ 4  9]
 [12 29]]
[[ 4  9]
 [12 29]]

 [[ True  True]
 [ True  True]]
29


In [23]:
# by specifying the axis parameter you can apply an operation along the specified axis of an array
b=np.arange(12).reshape(3,4)
print(b)
x=b.sum(axis=0) # performing the sum action in the specified axix i.e 0
print("\n The sum of axis 0 is",x)# i.e 0+4+8=12 , 1+5+9=15
x=b.min(axis=0)# if the axis=0 it performs the operation on each coloum and forms the single row
y=b.min(axis=1)# if the axis=1 it performs the operation on row 
print(x)
print(y)
a=np.arange(10)
print(a)
a[::2]=1000;# it means from the start to postion 6 ,exclusively set every 2nd element to -1000 
print(a)
print(a[::-1])# reversed the content of a
print(a[...,-1])# same as above i.e a[:,:,-1] reverse of a
for x in m:
    print(x)
x=list([[12,3,4],[1,3,3]])
for t in x:
    print(t)
# resize() modifies the array itshelf but reshape() returns the argument with modified shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 The sum of axis 0 is [12 15 18 21]
[0 1 2 3]
[0 4 8]
[0 1 2 3 4 5 6 7 8 9]
[1000    1 1000    3 1000    5 1000    7 1000    9]
[   9 1000    7 1000    5 1000    3 1000    1 1000]
9
[4 9]
[12 29]
[12, 3, 4]
[1, 3, 3]


In [11]:
# if the dimension is given as -1 in reshaping operation , then other dimension are automatically # if the dimension is given as -1 in reshaping operation , then other dimension are
# automatically 
x=np.arange(21);
x.reshape(7,-1)# reshape()  returns the argument with modified shape.
print(x)
x.resize(7,3)# But resize() modifies the array itshelf 
print(x)
# id is unique identifier of an object
# python passes the mutable object as reference, so function calls make no copy

# view() creates the new array object that looks at the same data i.e when one object item is changed then then new 
# object also contains same data as in x and y object respectively
y=x.view()
y is x
y[6,2]=2232
print("\n sadfa",y)
print(x)

# copy() methods make the complete copy of the array and its data 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]

 sadfa [[   0    1    2]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]
 [  15   16   17]
 [  18   19 2232]]
[[   0    1    2]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]
 [  15   16   17]
 [  18   19 2232]]
